/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ContentField,
  FieldData,
  ImageFieldData,
  LinkFieldData,
} from './models/content-models';
import {
  ContentMode,
} from './models/component-models';


export namespace Components {
  interface AlyContentField {
    'setField': (field: ContentField<any>) => Promise<void>;
    'setMode': (mode: ContentMode) => Promise<void>;
  }
  interface AlyContentFieldDefault {
    'field': FieldData<any>;
  }
  interface AlyContentFieldEditor {
    'field': FieldData<any>;
  }
  interface AlyHtmlField {
    'field': FieldData<any>;
  }
  interface AlyHtmlFieldEditor {
    'field': FieldData<any>;
  }
  interface AlyImageField {
    'field': FieldData<ImageFieldData>;
  }
  interface AlyImageFieldEditor {
    'field': FieldData<ImageFieldData>;
  }
  interface AlyLinkField {
    'field': FieldData<LinkFieldData>;
  }
  interface AlyLinkFieldEditor {
    'field': FieldData<LinkFieldData>;
  }
  interface AlyTextField {
    'field': FieldData<string>;
  }
  interface AlyTextFieldEditor {
    'field': FieldData<string>;
  }
}

declare global {


  interface HTMLAlyContentFieldElement extends Components.AlyContentField, HTMLStencilElement {}
  var HTMLAlyContentFieldElement: {
    prototype: HTMLAlyContentFieldElement;
    new (): HTMLAlyContentFieldElement;
  };

  interface HTMLAlyContentFieldDefaultElement extends Components.AlyContentFieldDefault, HTMLStencilElement {}
  var HTMLAlyContentFieldDefaultElement: {
    prototype: HTMLAlyContentFieldDefaultElement;
    new (): HTMLAlyContentFieldDefaultElement;
  };

  interface HTMLAlyContentFieldEditorElement extends Components.AlyContentFieldEditor, HTMLStencilElement {}
  var HTMLAlyContentFieldEditorElement: {
    prototype: HTMLAlyContentFieldEditorElement;
    new (): HTMLAlyContentFieldEditorElement;
  };

  interface HTMLAlyHtmlFieldElement extends Components.AlyHtmlField, HTMLStencilElement {}
  var HTMLAlyHtmlFieldElement: {
    prototype: HTMLAlyHtmlFieldElement;
    new (): HTMLAlyHtmlFieldElement;
  };

  interface HTMLAlyHtmlFieldEditorElement extends Components.AlyHtmlFieldEditor, HTMLStencilElement {}
  var HTMLAlyHtmlFieldEditorElement: {
    prototype: HTMLAlyHtmlFieldEditorElement;
    new (): HTMLAlyHtmlFieldEditorElement;
  };

  interface HTMLAlyImageFieldElement extends Components.AlyImageField, HTMLStencilElement {}
  var HTMLAlyImageFieldElement: {
    prototype: HTMLAlyImageFieldElement;
    new (): HTMLAlyImageFieldElement;
  };

  interface HTMLAlyImageFieldEditorElement extends Components.AlyImageFieldEditor, HTMLStencilElement {}
  var HTMLAlyImageFieldEditorElement: {
    prototype: HTMLAlyImageFieldEditorElement;
    new (): HTMLAlyImageFieldEditorElement;
  };

  interface HTMLAlyLinkFieldElement extends Components.AlyLinkField, HTMLStencilElement {}
  var HTMLAlyLinkFieldElement: {
    prototype: HTMLAlyLinkFieldElement;
    new (): HTMLAlyLinkFieldElement;
  };

  interface HTMLAlyLinkFieldEditorElement extends Components.AlyLinkFieldEditor, HTMLStencilElement {}
  var HTMLAlyLinkFieldEditorElement: {
    prototype: HTMLAlyLinkFieldEditorElement;
    new (): HTMLAlyLinkFieldEditorElement;
  };

  interface HTMLAlyTextFieldElement extends Components.AlyTextField, HTMLStencilElement {}
  var HTMLAlyTextFieldElement: {
    prototype: HTMLAlyTextFieldElement;
    new (): HTMLAlyTextFieldElement;
  };

  interface HTMLAlyTextFieldEditorElement extends Components.AlyTextFieldEditor, HTMLStencilElement {}
  var HTMLAlyTextFieldEditorElement: {
    prototype: HTMLAlyTextFieldEditorElement;
    new (): HTMLAlyTextFieldEditorElement;
  };
  interface HTMLElementTagNameMap {
    'aly-content-field': HTMLAlyContentFieldElement;
    'aly-content-field-default': HTMLAlyContentFieldDefaultElement;
    'aly-content-field-editor': HTMLAlyContentFieldEditorElement;
    'aly-html-field': HTMLAlyHtmlFieldElement;
    'aly-html-field-editor': HTMLAlyHtmlFieldEditorElement;
    'aly-image-field': HTMLAlyImageFieldElement;
    'aly-image-field-editor': HTMLAlyImageFieldEditorElement;
    'aly-link-field': HTMLAlyLinkFieldElement;
    'aly-link-field-editor': HTMLAlyLinkFieldEditorElement;
    'aly-text-field': HTMLAlyTextFieldElement;
    'aly-text-field-editor': HTMLAlyTextFieldEditorElement;
  }
}

declare namespace LocalJSX {
  interface AlyContentField extends JSXBase.HTMLAttributes<HTMLAlyContentFieldElement> {}
  interface AlyContentFieldDefault extends JSXBase.HTMLAttributes<HTMLAlyContentFieldDefaultElement> {
    'field'?: FieldData<any>;
  }
  interface AlyContentFieldEditor extends JSXBase.HTMLAttributes<HTMLAlyContentFieldEditorElement> {
    'field'?: FieldData<any>;
  }
  interface AlyHtmlField extends JSXBase.HTMLAttributes<HTMLAlyHtmlFieldElement> {
    'field'?: FieldData<any>;
  }
  interface AlyHtmlFieldEditor extends JSXBase.HTMLAttributes<HTMLAlyHtmlFieldEditorElement> {
    'field'?: FieldData<any>;
    'onEdit'?: (event: CustomEvent<any>) => void;
  }
  interface AlyImageField extends JSXBase.HTMLAttributes<HTMLAlyImageFieldElement> {
    'field'?: FieldData<ImageFieldData>;
  }
  interface AlyImageFieldEditor extends JSXBase.HTMLAttributes<HTMLAlyImageFieldEditorElement> {
    'field'?: FieldData<ImageFieldData>;
  }
  interface AlyLinkField extends JSXBase.HTMLAttributes<HTMLAlyLinkFieldElement> {
    'field'?: FieldData<LinkFieldData>;
  }
  interface AlyLinkFieldEditor extends JSXBase.HTMLAttributes<HTMLAlyLinkFieldEditorElement> {
    'field'?: FieldData<LinkFieldData>;
  }
  interface AlyTextField extends JSXBase.HTMLAttributes<HTMLAlyTextFieldElement> {
    'field'?: FieldData<string>;
  }
  interface AlyTextFieldEditor extends JSXBase.HTMLAttributes<HTMLAlyTextFieldEditorElement> {
    'field'?: FieldData<string>;
  }

  interface IntrinsicElements {
    'aly-content-field': AlyContentField;
    'aly-content-field-default': AlyContentFieldDefault;
    'aly-content-field-editor': AlyContentFieldEditor;
    'aly-html-field': AlyHtmlField;
    'aly-html-field-editor': AlyHtmlFieldEditor;
    'aly-image-field': AlyImageField;
    'aly-image-field-editor': AlyImageFieldEditor;
    'aly-link-field': AlyLinkField;
    'aly-link-field-editor': AlyLinkFieldEditor;
    'aly-text-field': AlyTextField;
    'aly-text-field-editor': AlyTextFieldEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


